language: minimal
dist: bionic
addons:
  apt:
    packages:
    - python3-pip
    - python3-setuptools

install:
  - pip3 install --user codespell

script:
  - codespell --ignore-words-list=que $(git ls-files -- "*.asciidoc" "*.md")
